### PR TITLE
pkcs11: ignore error if CKA_ALWAYS_AUTHENTICATE is not supported

### PR DESCRIPTION
**Pull request by alonbl**

### CODE REVIEW

**Comment by alonbl** [comment]
@gilweis please check

**Comment by gilweis** [comment]
Thanks,
I'll check this soon.
Please change the "packaging/debian/changelog" datetime of version 0.2.0 (Tue, 26 Jul 2022 00:00:00 +0000) 
The debian install take this datetime to all files.

**Comment by gilweis** [comment]
Tested and working properly.
Please update "packaging/debian/changelog".
Thank!

**Comment by gilweis** [comment]
Tested with:
SoftHSM2
Yubikey
YubiHSM
LunaHSM

**Pull request merged**
